version: '3.8'
services:
  app:
    build: .
    ports:
      - "80:80"
    volumes:
      - ./games.log:/app/games.log
      - .:/app
      - /app/node_modules
    command: npm run start:dev
    environment:
      - NODE_ENV=development